name: merge main

# on: 
#   push:
#     branches:    
#       - main
#     paths:
#       - 'aws-rds/backend/**'
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:  
              - 'aws-rds/backend/**'
            path2:
              - 'aws-rds/frontend/**'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies and run test
        if: steps.filter.outputs.path1 == 'true'
        run: npm ci && npm test
        working-directory: ./aws-rds/backend
      
      - name: Install dependencies and run test
        if: steps.filter.outputs.path2 == 'true'
        run: npm ci && npm test
        working-directory: ./aws-rds/frontend/front

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:  
              - 'aws-rds/backend/**'
            path2:
              - 'aws-rds/frontend/**'

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set short SHA
        id: set_short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        if: steps.filter.outputs.path1 == 'true'
        run: |
          docker build --tag henriquelr/dves_api:latest aws-rds/backend/
          docker build --tag henriquelr/dves_api:${{ env.SHORT_SHA }} aws-rds/backend/

      - name: Build Docker image
        if: steps.filter.outputs.path2 == 'true'
        run: |
          docker build --tag henriquelr/meu-site-nginx:latest aws-rds/frontend/
          docker build --tag henriquelr/meu-site-nginx:${{ env.SHORT_SHA }} aws-rds/frontend/

      - name: Push Docker image
        if: steps.filter.outputs.path1 == 'true'
        run: |
          docker push henriquelr/dves_api:latest
          docker push henriquelr/dves_api:${{ env.SHORT_SHA }}
      
      - name: Push Docker image
        if: steps.filter.outputs.path2 == 'true'
        run: |
          docker push henriquelr/meu-site-nginx:latest
          docker push henriquelr/meu-site-nginx:${{ env.SHORT_SHA }}
