name: merge main

# on: 
#   push:
#     branches:    
#       - main
#     paths:
#       - 'aws-rds/backend/**'
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./aws-rds/backend

      - name: Run test 
        run: npm test
        working-directory: ./aws-rds/backend

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set short SHA
        id: set_short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --tag henriquelr/dves_api:latest aws-rds/backend/
          docker build --tag henriquelr/dves_api:${{ env.SHORT_SHA }} aws-rds/backend/

      - name: Push Docker image
        run: |
          docker push henriquelr/dves_api:latest
          docker push henriquelr/dves_api:${{ env.SHORT_SHA }}
